public static class LastNames
{
    public static string[] names =
    {
        "Pablo Ruiz y Picasso",  "Picasso",
        "Ulysses S. Grant",  "Grant",
        "Auguste Rodin",  "Rodin",
        "(François) Auguste (René) Rodin",  "Rodin",
        "Johann Sebastian Bach",  "J. S. Bach",
        "James Augustine Aloysius Joyce",  "Joyce",
        "Theodore \"Teddy\" Roosevelt",  "Theodore Roosevelt",
        "Peter Ilyich Tchaikovsky",  "Tchaikovsky",
        "Anne Shirley Blythe",  "Anne Blythe",
        "John Sidney McCain III",  "McCain",
        "John McCain",  "McCain",
        "Hans Christian Andersen",  "Andersen",
        "Robert Norman Munsch",  "Munsch",
        "Herman Melville",  "Melville",
        "Walt(er) Whitman",  "Walt Whitman",
        "Walt Whitman",  "Walter Whitman",
        "Walter Whitman",  "Whitman",
        "Frank Lloyd Wright",  "Wright",
        "Samuel Langhorne Clemens",  "Clemens",
        "Mark Twain",  "Twain",
        "Jennifer Lawrence",  "Lawrence",
        "Michelangelo di Lodovico Buonarroti Simoni",  "Michelangelo",
        "Michelangelo Merisi da Caravaggio",  "Michelangelo",
        "F(rancis) Scott (Key) Fitzgerald",  "Fitzgerald",
        "F. Scott Fitzgerald",  "Fitzgerald",
        "Vincent Willem van Gogh",  "van Gogh",
        "Stephen \"Steph\" Curry",  "Curry",
        "Ralph Waldo Emerson",  "Emerson",
        "Hannibal Barca",  "Hannibal",
        "Lewis Carroll",  "Carroll",
        "Charles Lutwidge Dodgson",  "Dodgson",
        "Jane Austen",  "Austen",
        "Richard Russell \"Rick\" Riordan",  "Riordan",
        "Robert Lee Frost",  "Frost",
        "Gautama Buddha",  "Buddha",
        "Siddhartha Gautama",  "Gautama",
        "Wolfgang Amadeus Mozart",  "Mozart",
        "Sherlock Holmes",  "Holmes",
        "Alfred Hitchcock",  "Hitchcock",
        "Washington Irving",  "Irving",
        "Dwight David Eisenhower",  "Eisenhower",
        "Marco Polo",  "Polo",
        "Gabriel Garcia Marquez",  "Garcia Marquez",
        "Central Intelligence Agency",  "CIA",
        "Jules Gabriel Verne",  "Verne",
        "Ku Klux Klan",  "KKK",
        "Edvard Munch",  "Munch",
        "John Brown",  "Brown",
        "Jonathan Swift",  "Swift",
        "Andrew Carnegie",  "Carnegie",
        "John Michael Green",  "Green",
        "Gregor Johann Mendel",  "Mendel",
        "Sir (Ahmed) Salman Rushdie",  "Rushdie",
        "Adam Smith",  "Smith",
        "C(live) S(taples) Lewis",  "Lewis",
        "Kurt Vonnegut, Jr.",  "Vonnegut",
        "Georgia (Totto)  O’Keeffe",  "O’Keeffe",
        "Sir Arthur Conan Doyle",  "Doyle",
        "Saint Joan of Arc",  "Joan of Arc",
        "Emily Elizabeth Dickinson",  "Dickinson",
        "Emily Dickinson",  "Dickinson",
        "Robert Louis (Balfour) Stevenson",  "Stevenson",
        "Cleopatra VII Philopator",  "Cleopatra",
        "Andrew “Andy” Warhol(a), Jr",  "Warhol",
        "George Gershwin",  "Gershwin",
        "Richard Wagner",  "Wagner",
        "H(erbert) G(eorge) Wells",  "Wells",
        "John Wilkes Booth",  "Booth",
        "Niccolò Machiavelli",  "Machiavelli",
        "Derek Jeter",  "Jeter",
        "Virgin Mary",  "Mary",
        "King Arthur Pendragon",  "King Arthur",
        "Jane Morris Goodall",  "Goodall",
        "Sigmund Freud",  "Freud",
        "Woodrow Wilson",  "Wilson",
        "Svante Arrhenius",  "Arrhenius",
        "Nick Carraway",  "Carraway",
        "Nick Carraway",  "Nick",
        "Ernest Hemingway",  "Hemingway",
        "(Heinz Alfred) \"Henry\" Kissinger",  "Kissinger",
        "Alfred, Lord Tennyson",  "Tennyson",
        "(Joseph Robinette) \"Joe\" Biden",  "Biden",
        "T(homas) S(tearns) Eliot",  "Eliot",
        "Isaac Asimov",  "Asimov",
        "Johannes Brahms",  "Brahms",
        "Justin Bieber",  "Bieber",
        "Andy Warhol",  "Warhol",
        "Emily Dickinson",  "Dickinson",
        "Simon Peter",  "Peter",
        "Pyotr Ilyich Tchaikovsky",  "Tchaikovsky",
        "Paul Ryan",  "Ryan",
        "Isaac Newton",  "Newton",
        "(Sigismund Schlomo) Sigmund Freud",  "Freud",
        "Michelangelo (di Lodovico) Buonarroti (Simoni)",  "Michelangelo",
        "Gaius Julius Caesar Augustus",  "Augustus",
        "Kurt Vonnegut",  "Vonnegut",
        "Jules Verne",  "Verne",
        "Salvador (Felipe Jacinto) DalÃ­",  "Dalí",
        "E(dward) E(stlin) Cummings",  "Cummings",
        "E(dward) E(stlin) Cummings",  "Cummings",
        "Louis Armstrong",  "Armstrong",
        "Johannes Kepler",  "Kepler",
        "Leo Tolstoy",  "Tolstoy",
        "Ronald (Wilson) Reagan",  "Reagan",
        "Gordon Korman",  "Korman",
        "George Frideric HÃ¤ndel",  "Händel",
        "William Jennings Bryan",  "Bryan",
        "Thomas Jefferson",  "Jefferson",
        "Hermione Granger",  "Hermione",
        "Hermione Granger",  "Granger",
        "Vincent (Willem) Van Gogh",  "Van Gogh",
        "John Boehner",  "Boehner",
        "Edvard Munch [MOONK]",  "Munch",
        "(Anna) Eleanor Roosevelt",  "Eleanor Roosevelt",
        "Marcel Duchamp",  "Duchamp",
        "William Cuthbert Faulkner",  "Faulkner",
        "Otto von Bismarck",  "Bismarck",
        "Attila the Hun",  "Attila",
        "George Orwell",  "Orwell",
        "Hugo Chavez",  "Chavez",
        "Marie-Joseph Paul Yves Roch Gilbert du Motier, Marquis de Lafayette",  "Lafayette",
        "Marquis de Lafayette",  "Lafayette",
        "Arthur Asher Miller",  "Miller",
        "Arthur Miller",  "Miller",
        "Alexander John \"Lex\" Luthor",  "Lex Luthor",
        "James Fenimore Cooper",  "Cooper",
        "Gabrielle \"Gabby\" Giffords",  "Giffords",
        "Fyodor Dostoevsky",  "Dostoevsky",
        "Antonio Vivaldi",  "Vivaldi",
        "Samuel Taylor Coleridge",  "Coleridge",
        "William Sydney Porter",  "Porter",
        "Napoleon Bonaparte",  "Bonaparte",
        "Napoleon Bonaparte",  "Napoleon",
        "Andrew Jackson",  "Jackson",
        "Jack London",  "London",
        "Alexander Calder",  "Calder",
        "Tom Sawyer",  "Tom",
        "Tom Sawyer",  "Sawyer",
        "Neil Gaiman",  "Gaiman",
        "SimÃ³n BolÃ­var",  "Bolívar",
        "Simón Bolívar",  "Bolívar",
        "Simon Bolivar",  "Bolivar",
        "Joseph Stalin",  "Stalin",
        "Katniss Everdeen",  "Everdeen",
        "Katniss Everdeen",  "Katniss",
        "Muammar al-Gaddafi",  "Gaddafi",
        "Gaius Julius Caesar",  "Caesar",
        "Richard I of England",  "Richard the Lionheart",
        "George Washington",  "Washington",
        "John Marshall",  "Marshall",
        "Duke  Ellington",  "Duke Ellington",
        "Duke Ellington",  "Ellington",
        "Augustus Caesar",  "Augustus",
        "Erwin Rommel",  "Rommel",
        "Nyota Uhura",  "Uhura",
        "Herbert Hoover",  "Hoover",
        "Henry James",  "James",
        "Roy Lichtenstein",  "Lichtenstein",
        "Sylvia Plath",  "Plath",
        "Bashar Hafez al-Assad",  "B. al-Assad",
        "King David",  "David",
        "Albert Camus",  "Camus",
        "Gustave Flaubert",  "Flaubert",
        "David Bowie",  "Bowie",
        "Leonardo Da Vinci",  "Da Vinci",
        "Sinclair Lewis",  "Lewis",
        "Chiang Kai-shek",  "Chiang",
        "Jean-Jacques Rousseau",  "Rousseau",
        "William Cullen Bryant",  "Bryant",
        "Antonio López de Santa Anna",  "Santa Anna",
        "Pablo Neruda",  "Neruda",
        "Holden Caulfield",  "Caulfield",
        "Leon Trotsky",  "Trotsky",
        "Linus Pauling",  "Pauling",
        "Arnold Schwarzenegger",  "Schwarzenegger",
        "Harold Pinter",  "Pinter",
        "Aaron Copland",  "Copland",
        "Anton Chekov",  "Chekov",
        "Frédéric Chopin",  "Chopin",
        "Achille-Claude Debussy",  "Debussy",
        "Claude Debussy",  "Debussy",
        "James Whistler",  "Whistler",
        "Frank Gehry",  "Gehry",
        "Alexander Hamilton",  "Hamilton",
        "Constantin Brancusi",  "Brancusi",
        "Eugene Delacroix",  "Delacroix",
        "Abraham Lincoln",  "Lincoln",
        "Ezra Pound",  "Pound",
        "James Joyce",  "Joyce",
        "Louis Pasteur",  "Pasteur",
        "Bertrand Russell",  "Russell",
        "Alan Turing",  "Turing",
        "Wallace Stevens",  "Stevens",
        "John Maynard Keynes",  "Keynes",
        "Pierre de Fermat",  "Fermat",
        "H. G. Wells",  "Wells",
        "Grant Wood",  "Wood",
        "Fyodor Dostoyevsky",  "Dostoyevsky",
        "Martin Luther",  "Luther",
        "William Gladstone",  "Gladstone",
        "Agatha Christie",  "Christie",
        "Lord Byron",  "Byron",
        "Eero Saarinen",  "Saarinen",
        "Lidwig van Beethoven",  "Beethoven",
        "Elizabeth Barrett Browning",  "Barrett Browning",
        "Johannes Vermeer",  "Vermeer",
        "Jorge Luis Borges",  "Borges",
        "Nelson Mandela",  "Mandela",
        "Fransisco Goya",  "Goya",
        "Gilbert Newton Lewis",  "Lewis",
        "William Carlos Williams",  "Williams",
        "William Butler Yeats",  "Yeats",
        "John Milton",  "Milton",
        "Giacomo Puccini",  "Puccini",
        "Stanley Kubrick",  "Kubrick",
        "Stephen Crane",  "Crane",
        "Isabel Allende",  "Allende",
        "Thomas Pynchon",  "Pynchon",
        "George III",  "George William Frederick",
        "Alfred the Great",  "Alfred I",
        "J. D. Salinger",  "Salinger",
        "Edgar Allen Poe",  "Poe",
        "Edgar Allan Poe",  "Poe",
        "Che Guevara",  "Guevara",
        "Henri Matisse",  "Matisse",
        "Leonard Bernstein",  "Bernstein",
        "Jeffrey Edward Epstein",  "Epstein",
        "Aldous Huxley",  "Huxley",
        "Ashoka Maurya",  "Ashoka",
        "Niels Bohr",  "Bohr",
        "Bob Dylan",  "Dylan",
        "Naurice Ravel",  "Ravel",
        "Don Giovanni",  "Giovanni",
        "Flannery O'Connor",  "O'Connor",
        "Margaret Thatcher",  "Thatcher",
        "Haruki Murakami",  "Murakami",
        "Judas Iscariot",  "Judas",
        "Oliver Cromwell",  "Cromwell",
        "Bernhard Riemann",  "Riemann",
        "Oscar Wilde",  "Wilde",
        "René Magritte",  "Magritte",
        "Rudyard Kipling",  "Kipling",
        "Jared Corey Kushner",  "Kushner",
        "Thomas Cole",  "Cole",
        "Andrew Wyeth",  "Wyeth",
        "Dmitri Shostakovich",  "Shostakovich",
        "Douglas MacArthur",  "MacArthur",
        "Kacey Musgraves",  "Musgraves",
        "Caroline Polachek",  "Polachek",
        "Dua Lipa",  "Lipa",
        "Pedro (Álvares) Cabral",  "Cabral",
        "Édouard Manet",  "Manet",
        "Jesus Christ",  "Jesus",
        "Jesus Christ",  "Christ",
        "Narendra Modi",  "Modi",
        "Gian Lorenzo Bernini",  "Bernini",
        "Chairman Mao Zedong",  "Mao Zedong",
        "Mao Zedong",  "Mao",
        "Robert (Alexander) Schumann",  "Schumann",
        "Milan Kundera",  "Kundera",
        "Diego (Rodríguez de Silva y) Velázquez",  "Velázquez",
        "Aung San Suu Kyi",  "Suu Kyi",
        "Aung San Suu Kyi",  "Aung San",
        "Emmanuel (Jean-Michel Frédéric) Macron",  "Macron",
        "August Wilson",  "Wilson",
        "Richard (Charles) Rodgers",  "Rodgers",
        "William James",  "James",
        "Kendrick Lamar",  "Kendrick",
        "Kendrick Lamar",  "Lamar",
        "Blanche DuBois",  "Blanche",
        "Thornton (Niven) Wilder",  "Wilder",
        "Beyoncé Knowles-Carter",  "Beyoncé",
        "Mark Antony",  "Antony",
        "Antoni Gaudí (i Cornet)",  "Gaudí",
        "Horatio Nelson",  "Nelson",
        "Chandragupta Maurya",  "Chandragupta",
        "Langston Hughes",  "Hughes",
        "Walther (Hermann) Nernst",  "Nernst",
        "Nathaniel Bacon",  "Bacon",
        "George Bernard Shaw",  "Shaw",
        "Susan B. Anthony",  "Anthony",
        "David Hume",  "Hume",
        "Thomas (Ruggles) Pynchon (Jr.)",  "Pynchon",
        "(Paul) Thomas Mann",  "Mann",
        "Evelyn Waugh",  "Waugh",
        "Franz Kafka",  "Kafka",
        "Derek (Alton) Walcott",  "Walcott",
        "George Frideric Handel",  "Handel",
        "Anish Kapoor",  "Kapoor",
        "Jacques Derrida",  "Derrida",
        "William Blake",  "Blake",
        "Silas Marner",  "Marner",
        "Charles Ives",  "Ives",
        "E. M. Forster",  "Forster",
        "Zora Neale Hurston",  "Hurston",
        "Lord Rayleigh",  "Rayleigh",
        "Michel de Montaigne",  "Montaigne",
        "Richard (\"REE-card\") Strauss",  "Strauss",
        "Lillian Hellman",  "Hellman",
        "Lillian (Florence) Hellman",  "Hellman",
        "Emma Bovary",  "Bovary",
        "Tim Berners-Lee",  "Berners-Lee",
        "Michael Collins",  "Collins",
        "Edgar Degas",  "Degas",
        "Nikita Khrushchev",  "Khrushchev",
        "Marcus Brutus",  "Brutus",
        "Franz Boas",  "Boas",
        "Chinua Achebe",  "Achebe",
        "Andrew Lloyd Webber",  "Lloyd Webber",
        "Michael Jordan",  "Jordan",
        "Ralph (“rafe”) Vaughan Williams",  "Williams",
        "Fidel Castro",  "Castro",
        "Peter Bruegel the Elder",  "Bruegel",
        "Lucian Freud",  "Freud",
        "Nicolaus Copernicus",  "Copernicus",
        "Benjamin Britten",  "Britten",
        "Antonio Canova",  "Canova",
        "Judith Weir",  "Weir",
        "Frederick Ashton",  "Ashton",
        "Immanuel Kant",  "Kant",
        "Sandro Botticelli",  "Botticelli",
        "Hector Berlioz",  "Berlioz",
        "Gotthold Ephraim",  "Ephraim",
        "Orlando Gibbons",  "Gibbons",
        "James Francis Edward Stuart",  "Old Pretender",
        "Maguib Mahfouz",  "Mahfouz",
        "William D. Hamilton",  "Hamilton",
        "Shah Jahan",  "Jahan",
        "Karl Marx",  "Marx",
        "Helmut Kohl",  "Marx",
        "Anne Sexton",  "Sexton",
        "Jalāl ad-Dīn Muḥammad Rūmī",  "Rūmī",
        "David Ricardo",  "Ricardo",
        "Bernard (Arthur Owen) Williams",  "Williams",
        "Hilary (Whitehall) Putnam",  "Putnam",
        "Neal (Leon) Cassady",  "Cassady",
        "Martin Luther King, Sr.",  "Father of MLK",
        "Tristan Tzara",  "Tzara",
        "Richard Feynman",  "Feynman",
        "Eugene (Gladstone) O'Neill",  "O'Neill",
        "Sor Juana Inés de la Cruz",  "Juana",
        "Carlo Ginzburg",  "Ginzburg",
        "Horace Walpole",  "Walpole",
        "River Thames",  "Thames",
        "Merce Cunningham",  "Cunningham",
        "Bill Evans",  "Evans",
        "Rainer Maria Rilke",  "Rilke",
        "Saint Anthony",  "Anthony",
        "Max Beerbohm",  "Beerbohm",
        "Marcel Proust",  "Proust",
        "Philip Larkin",  "Larkin",
        "Raymond Queneau",  "Queneau",
        "Jennifer Egan",  "Egan",
        "Matt Bevin",  "Bevin",
        "Steven Weinberg",  "Weinberg",
        "Marlon James",  "James"
        
    };
}