public static class Nouns
{
    public static string[] nouns =
    {
        "ballet",  "ballets",
        "flute",  "flutes",
        "string instrument",  "string instruments",
        "landscape",  "landscapes",
        "piano",  "pianos",
        "waltz",  "waltzes",
        "clarinet",  "clarinets",
        "photograph",  "photographs",
        "trumpet",  "trumpets",
        "boat",  "boats",
        "ship",  "ships",
        "concerto",  "concertos",
        "saxophone",  "saxophones",
        "sculpture",  "sculptures",
        "violin",  "violins",
        "chromatic scale",  "chromatic scales",
        "opera",  "operas",
        "soprano",  "sopranos",
        "non-biodegradable plastic bag",  "non-biodegradable plastic bags",
        "coal",  "coals",
        "electric chair",  "electric chairs",
        "egyptian pyramid",  "egyptian pyramids",
        "cosmonaut",  "cosmonauts",
        "longbow",  "longbows",
        "missile",  "missiles",
        "pyramid",  "pyramids",
        "military",  "militaries",
        "bird",  "birds",
        "metaphor",  "metaphors",
        "diamond",  "diamonds",
        "sonnet",  "sonnets",
        "wine",  "wines",
        "Homer",  "Homeros",
        "short story",  "short stories",
        "essay",  "essays",
        "fable",  "fables",
        "gun",  "guns",
        "ode",  "odes",
        "mirror",  "mirrors",
        "ocean",  "oceans",
        "dog",  "dogs",
        "titan",  "titans",
        "aztec Empire",  "aztecs",
        "paradox",  "paradoxes",
        "locust",  "locusts",
        "sin",  "sins",
        "angel",  "angels",
        "resistor",  "resistors",
        "comet",  "comets",
        "solution",  "solutions",
        "chemical bond",  "chemical bonds",
        "x-ray",  "x-rays",
        "surface wave",  "surface waves",
        "matrix",  "matrices",
        "neutron",  "neutrons",
        "rainforest",  "rainforests",
        "line",  "lines",
        "chloroplast",  "chloroplasts",
        "function",  "functions",
        "ion",  "ions",
        "meteor shower",  "meteor showers",
        "black hole",  "black holes",
        "base",  "bases",
        "space telescope",  "space telescopes",
        "circle",  "circles",
        "proton",  "protons",
        "protein",  "proteins",
        "vascular plant",  "vascular plants",
        "rational number",  "rational numbers",
        "pendulum",  "pendulums",
        "virus",  "viruses",
        "kidney",  "kidneys",
        "tectonic plate",  "tectonic plates",
        "noble gas",  "noble gases",
        "tornado",  "tornados",
        "root",  "roots",
        "electron",  "electrons",
        "hydrogen bond",  "hydrogen bonds",
        "set",  "sets",
        "amino acid",  "amino acids",
        "supernova",  "supernovas",
        "supernovae",  "supernovas",
        "vestigial",  "vestigial structures",
        "boson",  "bosons",
        "regular hexagon",  "regular hexagons",
        "alcohol",  "alcohols",
        "calorimeter",  "calorimeters",
        "parabola",  "parabolas",
        "sequence",  "sequences",
        "galaxy",  "galaxies",
        "phenotype",  "phenotypes",
        "slope",  "slopes",
        "snowflake",  "snowflakes",
        "hexagon",  "hexagons",
        "flower",  "flowers",
        "hormone",  "hormones",
        "programming language",  "programming languages",
        "square number",  "square numbers",
        "perfect square",  "perfect squares",
        "glacier",  "glaciers",
        "coral reef",  "coral reefs",
        "calorie",  "calories",
        "isotope",  "isotopes",
        "hard disk drive",  "hard disk drives",
        "snake",  "snake",
        "keyboard",  "keyboards",
        "fat",  "fats",
        "honey bee",  "honey bees",
        "polynomial",  "polynomials",
        "ultrasonic frequency",  "ultrasonic frequencies",
        "sunspot",  "sunspots",
        "mathematical proof",  "mathematical proofs",
        "parasite",  "parasites",
        "prime number",  "prime numbers",
        "lung",  "lungs",
        "ribosome",  "ribosomes",
        "solar eclipse",  "solar eclipses",
        "tectonic plate",  "tectonic plates",
        "greatest common factor",  "greatest common factors",
        "vitamin",  "vitamins",
        "coefficient",  "coefficients",
        "solid",  "solids",
        "leaf",  "leaves",
        "skyscraper",  "skyscrapers",
        "cloud",  "clouds",
        "dwarf planet",  "dwarf planets",
        "fungus",  "fungi",
        "cancer",  "cancers",
        "median",  "medians",
        "integer",  "integers",
        "tundra",  "tundras",
        "acid",  "acids",
        "fractal",  "fractals",
        "frequency",  "frequencies",
        "muscle",  "muscles",
        "parallelogram",  "parallelograms",
        "tide",  "tides",
        "inequality",  "inequalities",
        "discriminant",  "discriminants",
        "liver",  "livers",
        "tooth",  "teeth",
        "rectangle",  "rectangles",
        "asteroid",  "asteroids",
        "mean",  "means",
        "solution",  "solutions",
        "moon",  "moons",
        "triangle",  "triangles",
        "mitochondrion",  "mitochondria",
        "lever",  "levers",
        "volcano",  "volcanoes",
        "supply",  "supplies",
        "memory",  "memories",
        "personality",  "personalities",
        "interest rate",  "interest rates",
        "eye",  "eyes",
        "poll",  "polls",
        "webcomic",  "webcomics",
        "knight",  "knights",
        "onion",  "onions",
        "girl scout cookie",  "girl scout cookies",
        "cheese",  "cheeses",
        "trombone",  "trombones",
        "horse",  "horses",
        "mass",  "masses",
        "rhapsody",  "rhapsodies",
        "fountain",  "fountains",
        "symphony",  "symphonies",
        "dome",  "domes",
        "march",  "marches",
        "isthmus",  "isthmuses",
        "mongols",  "mongolian empire",
        "currency",  "currencies",
        "tariff",  "tariffs",
        "boer",  "boers",
        "jew",  "jews",
        "airplane",  "airplanes",
        "capital punishment",  "capital punishments",
        "huns",  "hunnic empire",
        "chariot",  "chariots",
        "labor union",  "labor unions",
        "huguenot",  "huguenots",
        "monarchy",  "monarchies",
        "slave revolt",  "slave revolts",
        "viking",  "vikings",
        "frog",  "frogs",
        "diary",  "diaries",
        "pig",  "pigs",
        "butler",  "butlers",
        "tree",  "trees",
        "underworld",  "underworlds",
        "centaur",  "centaurs",
        "ancient egyptian sun god",  "ancient egyptian sun gods",
        "river",  "rivers",
        "wind",  "winds",
        "spider",  "spiders",
        "war deity",  "war deities",
        "sun deity",  "sun deities",
        "fox",  "foxes",
        "giant",  "giants",
        "dragon",  "dragons",
        "sword",  "swords",
        "bull",  "bulls",
        "cow",  "cows",
        "language",  "languages",
        "mosque",  "mosques",
        "confession",  "confessions",
        "buffer solution",  "buffer solutions",
        "sorting algorithm",  "sorting algorithms",
        "longitudinal wave",  "longitudinal waves",
        "owl",  "owls",
        "polymer",  "polymers",
        "marsupial",  "marsupials",
        "echinoderm",  "echinoderms",
        "red blood cell",  "red blood cells",
        "composite number",  "composite numbers",
        "diode",  "diodes",
        "quark",  "quarks",
        "igneous rock",  "igneous rocks",
        "nematode",  "nematodes",
        "catalyst",  "catalysts",
        "laser",  "lasers",
        "prime",  "primes",
        "transition metal",  "transition metals",
        "buffer",  "buffers",
        "vertical line",  "vertical lines",
        "complex number",  "complex numbers",
        "cell",  "cells",
        "geyser",  "geysers",
        "cnidarian",  "cnidarians",
        "arthropod",  "arthropods",
        "tsunami",  "tsunamis",
        "quadratic polynomial",  "quadratic polynomials",
        "quadratic equation",  "quadratic equations",
        "metalloid",  "metalloids",
        "vector",  "vectors",
        "neutron star",  "neutron stars",
        "cirrus cloud",  "cirrus clouds",
        "enzyme",  "enzymes",
        "neanderthal",  "neanderthals",
        "real number",  "real numbers",
        "colloid",  "colloids",
        "chordate",  "chordates",
        "battery",  "batteries",
        "fault",  "faults",
        "crystal",  "crystals",
        "lysosome",  "lysosomes",
        "nuclei",  "nucleus",
        "alkali metal",  "alkali metals",
        "neuron",  "neurons",
        "gymnosperm",  "gymnosperms",
        "liquid",  "liquids",
        "fibonacci number",  "fibonacci numbers",
        "bone",  "bones",
        "capacitor",  "capacitors",
        "antibody",  "antibodies",
        "mollusk",  "mollusks",
        "desert",  "deserts",
        "plasma",  "plasmas",
        "plasmid",  "plasmids",
        "sedimentary rock",  "sedimentary rocks",
        "halogen",  "halogens",
        "logarithm",  "logarithms",
        "sponge",  "sponges",
        "hyperbola",  "hyperbolas",
        "combustion reaction",  "combustion reactions",
        "neutrino",  "neutrinos",
        "superconductor",  "superconductors",
        "crime",  "crimes",
        "chimpanzee",  "chimpanzees",
        "magician",  "magicians",
        "spam email",  "spam emails",
        "cat",  "cats",
        "mayor",  "mayors",
        "abortion",  "abortions",
        "charter school",  "charter schools",
        "mural",  "murals",
        "tapestry",  "tapestries",
        "string quartet",  "string quartets",
        "bassoon",  "bassoons",
        "dress",  "dresses",
        "ocean liner",  "ocean liners",
        "pipe organ",  "pipe organs",
        "opera house",  "opera houses",
        "overture",  "overtures",
        "bass",  "basses",
        "circus",  "circuses",
        "soldier",  "soldiers",
        "skull",  "skulls",
        "violin concerto",  "violin concertos",
        "transverse flute",  "transverse flutes",
        "self-portrait",  "self-portraits",
        "clown",  "clowns",
        "piano sonata",  "piano sonatas",
        "piano concerti",  "piano concertos",
        "french horn",  "french horns",
        "chair",  "chairs",
        "shark",  "sharks",
        "toy",  "toys",
        "train",  "trains",
        "museum",  "museums",
        "vase",  "vases",
        "bowl of fruit",  "bowls of fruit",
        "opera singer",  "opera singers",
        "dance",  "dances",
        "lion",  "lions",
        "harp",  "harps",
        "swan",  "swans",
        "choreographer",  "choreographers",
        "drum",  "drums",
        "violoncello",  "violoncellos",
        "dancer",  "dancers",
        "oboe",  "oboes",
        "sonata",  "sonatas",
        "palace",  "palaces",
        "egg",  "eggs",
        "doctor",  "doctors",
        "galaxy/ies",  "galaxy",
        "death/execution by beheading",  "death by beheading",
        "death/execution by beheading",  "execution by beheading",
        "aqueduct",  "aqueducts",
        "baseball stadium",  "baseball stadiums",
        "magnetic field",  "magnetic fields",
        "satyr",  "satyrs",
        "bunker",  "bunkers",
        "slave",  "slaves",
        "riddle",  "riddles",
        "russian jew",  "russian jews",
        "rainbow",  "rainbows",
        "us flag",  "us flags",
        "nuclear power plant",  "nuclear power plants",
        "mammal",  "mammals",
        "t cell",  "t cells",
        "garden",  "gardens",
        "monkey",  "monkeys",
        "slav",  "slavs",
        "thunderstorm",  "thunderstorms",
        "quaker",  "quakers",
        "window",  "windows",
        "conditional statement",  "conditional statements",
        "penguin",  "penguins",
        "chinese muslim",  "chinese muslims",
        "sikh guru",  "sikh gurus",
        "philosopher",  "philosophers",
        "railroad",  "railroads",
        "mezzo-soprano",  "mezzo-sopranos",
        "hominin",  "hominins",
        "(near-earth) asteroid",  "(near-earth) asteroids",
        "basic condition",  "basic conditions",
        "elephant",  "elephants",
        "vibration",  "vibrations",
        "electric charge",  "electric charges",
        "prison",  "prisons",
        "trolley",  "trolleys",
        "shaman",  "shamans",
        "cadence",  "cadences",
        "hydrogen",  "hydrogens",
        "chaperone",  "chaperones",
        "shipping container",  "shipping containers",
        "corporation",  "corporations",
        "human",  "humans",
        "banana",  "bananas",
        "race",  "races",
        "pipe",  "pipes",
        "biography",  "biographies",
        "melting pot",  "melting pots",
        "HIV/AIDS",  "hiv",
        "HIV/AIDS",  "aids",
        "tsar",  "tsars",
        "disproportionation reaction",  "disproportionation reactions",
        "tea party",  "tea parties",
        "lightning bolt",  "lightning bolts",
        "ritual dance",  "ritual dances",
        "planet",  "planets",
        "algorithm",  "algorithms",
        "serpent",  "serpents",
        "scientist",  "scientists",
        "wage",  "wages",
        "cell nuclei",  "cell nucleus",
        "pharaoh",  "pharaohs",
        "the wheel",  "wheel",
        "wheel",  "wheels",
        "island",  "islands",
        "miniature",  "miniatures",
        "camel",  "camels",
        "El ingenioso hidalgo Don Quijote de la Mancha",  "Don Quixote",
        "mask",  "masks",
        "sculpture park",  "sculpture parks",
        "gray wolf",  "gray wolves",
        "roman satire",  "roman satires",
        "coal miner",  "coal miners",
        "facial expression",  "facial expressions",
        "mosaic",  "mosaics",
        "turtle",  "turtles",
        "Ancestral Pueblo",  "Pueblo",
        "amide",  "amides",
        "arithmetic progression",  "arithmetic progressions",
        "gravitational wave",  "gravitational waves",
        "gravitational wave frequency",  "gravitational wave frequencies",
        "business cycle",  "business cycles"
    };
}